# Generated by Django 3.1.7 on 2021-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.IntegerField()),
                ('start_call', models.DateTimeField(blank=True, null=True)),
                ('end_call', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=13, null=True)),
                ('destination', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
    ]
