# Generated by Django 3.1.7 on 2021-03-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_call', models.DateTimeField()),
                ('end_call', models.DateTimeField()),
                ('source', models.CharField(max_length=13)),
                ('destination', models.CharField(max_length=13)),
            ],
        ),
    ]
