# Generated by Django 3.1.7 on 2021-03-26 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='start_call',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 22, 42, 15, 750855)),
        ),
    ]
