# Generated by Django 3.1.7 on 2021-03-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('call_id', 'type_call')},
        ),
    ]
