# Generated by Django 3.1.7 on 2021-03-23 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_bill'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='initial_call',
        ),
    ]
